// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdg1lK6nqY1BsNE85gkpiFEsFC-LQkyBM',
    appId: '1:1080393734575:web:b24d72c998632d625f375a',
    messagingSenderId: '1080393734575',
    projectId: 'calcount-f6f51',
    authDomain: 'calcount-f6f51.firebaseapp.com',
    storageBucket: 'calcount-f6f51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsZjm0pBUKjrcTskhdMUgnYTk8WnQJklw',
    appId: '1:1080393734575:android:f7980e3fcb35e7195f375a',
    messagingSenderId: '1080393734575',
    projectId: 'calcount-f6f51',
    storageBucket: 'calcount-f6f51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Pep9RZEfOM_p6hraEetXES5FNN_1HT8',
    appId: '1:1080393734575:ios:fa8b1488165c28d35f375a',
    messagingSenderId: '1080393734575',
    projectId: 'calcount-f6f51',
    storageBucket: 'calcount-f6f51.appspot.com',
    iosBundleId: 'com.example.calcount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Pep9RZEfOM_p6hraEetXES5FNN_1HT8',
    appId: '1:1080393734575:ios:fa8b1488165c28d35f375a',
    messagingSenderId: '1080393734575',
    projectId: 'calcount-f6f51',
    storageBucket: 'calcount-f6f51.appspot.com',
    iosBundleId: 'com.example.calcount',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdg1lK6nqY1BsNE85gkpiFEsFC-LQkyBM',
    appId: '1:1080393734575:web:3e4b7655e76f6dd55f375a',
    messagingSenderId: '1080393734575',
    projectId: 'calcount-f6f51',
    authDomain: 'calcount-f6f51.firebaseapp.com',
    storageBucket: 'calcount-f6f51.appspot.com',
  );
}
